### ISSUE TITLE
Categories are not filled up by default

### ISSUE THREAD

**Issue by degroundshaker** [rishiv3/ebayAddItem#1]
I checked out your code, but few things are not working. 
For example: Primary Categories must be autofilled by default. But you are using a POST variable ['category'] out of nowhere.

**Comment by madhusudhan1234** [comment]
I am also getting this problem here .

**Comment by rishiv3** [comment]
Sorry but It was meant in that way.
But I have created one category selection page and I will push it soon.

**Comment by jairus0893** [comment]
Hi @rishiv3  im getting error on this also. do u have the latest one? Thanks

**Comment by rishiv3** [comment]
Hello Everyone,

I have added the code for category and fixed few issues also.
Please check and let me know if you found anything.

Kind Regards,
Rishi
