### ISSUE TITLE
token error 

### ISSUE THREAD

**Issue by hassanrafiq** [rishiv3/ebayAddItem#6]
categories are not being fetched the script is not working...

**Comment by rishiv3** [comment]
At least provide some sort of details. Like, what was the error? What and how you have configured it?
Opening an issue, telling it's not working won't help.

Closing for now. If you have any details, reopen it again.

**Comment by hassanrafiq** [comment]
I added api I get categories but it is not showing the api

**Comment by rishiv3** [comment]
What do you mean "it is not showing the api"?
